const ADDRESS = "Jl. Telaga Mas Raya No.10, Talaga, Kec. Cikupa, Kabupaten Tangerang, Banten 15710, Indonesia";
const PHONE = "+62 21 59401278";
const EMAIL = "daesoungcs@daesoung.com";
const PLACE_ID = "ChIJr8Kfc8UAQi4RPBeOlv4Rq6g";
const MAP_QUERY = `${"PT.Daesoung Electric Components"}, ${ADDRESS}`;
const MAP_EMBED = `https://www.google.com/maps?q=${encodeURIComponent(MAP_QUERY)}&output=embed`;
const MAP_LINK = `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent("PT.Daesoung Electric Components")}&query_place_id=${PLACE_ID}`;

function PhoneIcon() { return <svg viewBox="0 0 24 24" className="h-6 w-6 fill-current" aria-hidden="true"><path d="M6.6 10.8c1.5 3 3.6 4.9 6.6 6.6l2.2-2.2c.3-.3.8-.4 1.2-.2 1.3.4 2.7.7 3.9.7.6 0 1 .4 1 1V20c0 .6-.4 1-1 1C11.2 21 3 12.8 3 2.5c0-.6.4-1 1-1h3.3c.6 0 1 .4 1 1 0 1.3.2 2.6.7 3.9.1.4 0 .9-.3 1.2l-2.1 2.2Z" /></svg>; }
function EmailIcon() { return <svg viewBox="0 0 24 24" className="h-7 w-7 fill-none stroke-current" strokeWidth="2" aria-hidden="true"><path d="M3 5h18v14H3z" /><path d="m3 6 9 7 9-7" /></svg>; }

export default function Contact() {
  return (
    <main className="min-h-screen bg-white text-slate-800">
      <section className="bg-green-800 px-6 py-32 text-white"><div className="mx-auto max-w-6xl"><p className="mb-5 text-sm font-semibold tracking-[0.3em] text-green-300">CONTACT</p><h1 className="text-5xl font-bold tracking-tight md:text-6xl">Get In Touch</h1><p className="mt-8 max-w-2xl text-lg leading-8 text-green-50">We welcome your inquiries regarding wire harness, electronic components and customized manufacturing solutions.</p></div></section>
      <section className="px-6 py-24"><div className="mx-auto max-w-[1400px]"><p className="text-sm font-semibold tracking-[0.25em] text-green-700">CONTACT US</p><h2 className="mt-4 text-4xl font-bold text-slate-900 md:text-5xl">DAESOUNG ELECTRIC COMPONENTS</h2><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-600">Please contact us for product inquiries, quotations, manufacturing partnerships or any other business questions.</p><div className="mt-14 grid gap-8 lg:grid-cols-[1.08fr_0.92fr]"><div className="space-y-6"><div className="rounded-2xl border border-slate-200 p-8"><p className="text-sm font-semibold tracking-[0.2em] text-green-700">ADDRESS</p><h3 className="mt-4 text-2xl font-bold text-slate-900">Indonesia Factory</h3><p className="mt-4 leading-7 text-slate-600">{ADDRESS}</p></div><div className="grid gap-6 sm:grid-cols-2"><div className="rounded-2xl border border-slate-200 p-8"><p className="text-sm font-semibold tracking-[0.2em] text-green-700">PHONE</p><a href="tel:+622159401278" className="mt-5 flex items-center gap-3 whitespace-nowrap text-[17px] font-bold tracking-tight text-slate-900 hover:text-green-700 sm:text-[18px]"><span className="flex h-12 w-12 shrink-0 items-center justify-center rounded-full bg-green-600 text-white"><PhoneIcon /></span><span>{PHONE}</span></a></div><div className="rounded-2xl border border-slate-200 p-8"><p className="text-sm font-semibold tracking-[0.2em] text-green-700">EMAIL</p><a href={`mailto:${EMAIL}`} className="mt-5 flex items-center gap-3 whitespace-nowrap text-[16px] font-bold tracking-[-0.02em] text-slate-900 hover:text-green-700 sm:text-[17px] lg:text-[18px]"><span className="flex h-12 w-12 shrink-0 items-center justify-center rounded-full bg-green-600 text-white"><EmailIcon /></span><span>{EMAIL}</span></a></div></div><div className="rounded-2xl border border-slate-200 p-8"><p className="text-sm font-semibold tracking-[0.2em] text-green-700">BUSINESS</p><p className="mt-4 leading-7 text-slate-600">Wire Harness<br />Electronic Components<br />Custom Solutions</p></div></div><div className="overflow-hidden rounded-2xl border border-slate-200 bg-slate-100 shadow-sm"><iframe title="DAESOUNG ELECTRIC COMPONENTS location on Google Maps" src={MAP_EMBED} className="h-[520px] w-full border-0" loading="lazy" referrerPolicy="no-referrer-when-downgrade" /><div className="flex items-center justify-between gap-4 border-t border-slate-200 bg-white px-6 py-5"><p className="text-sm text-slate-600">Find our facility on Google Maps.</p><a href={MAP_LINK} target="_blank" rel="noreferrer" className="shrink-0 rounded-full bg-green-700 px-5 py-3 text-sm font-semibold text-white transition hover:bg-green-800">Open Google Maps ↗</a></div></div></div></div></section>
      <section className="bg-slate-50 px-6 py-24"><div className="mx-auto max-w-4xl text-center"><p className="text-sm font-semibold tracking-[0.25em] text-green-700">INQUIRY</p><h2 className="mt-4 text-4xl font-bold text-slate-900 md:text-5xl">Contact Us by Email</h2><p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-slate-600">For product inquiries, quotations, manufacturing partnerships, or other business inquiries, please contact us by email. We will review your message and get back to you as soon as possible.</p><div className="mx-auto mt-12 max-w-2xl rounded-3xl border border-green-100 bg-white px-8 py-10 shadow-sm"><span className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-green-700 text-white"><EmailIcon /></span><p className="mt-6 text-sm font-semibold tracking-[0.2em] text-green-700">EMAIL</p><a href={`mailto:${EMAIL}`} className="mt-3 inline-block break-all text-2xl font-bold text-slate-900 transition hover:text-green-700 md:text-3xl">{EMAIL}</a><div className="mt-8"><a href={`mailto:${EMAIL}?subject=${encodeURIComponent("Website Inquiry - DAESOUNG ELECTRIC COMPONENTS")}`} className="inline-flex rounded-full bg-green-700 px-9 py-4 font-semibold text-white transition hover:bg-green-800">SEND EMAIL</a></div></div></div></section>
      <section className="bg-green-800 px-6 py-20 text-white"><div className="mx-auto max-w-6xl text-center"><p className="text-sm font-semibold tracking-[0.25em] text-green-300">DAESOUNG ELECTRIC COMPONENTS</p><h2 className="mt-4 text-3xl font-bold md:text-4xl">Your Reliable Manufacturing Partner</h2><p className="mx-auto mt-5 max-w-2xl leading-7 text-green-50">We look forward to discussing your requirements and building a long-term business relationship.</p></div></section>
    </main>
  );
}
