export default function Home() {
  const strengths = [
    ["Quality First", "Structured quality controls from incoming inspection through final inspection."],
    ["Manufacturing Capability", "Stable production systems built around wire harness and electronic component assembly."],
    ["Skilled Team", "Experienced operators and disciplined processes support consistent production quality."],
    ["Reliable Delivery", "Production planning and process control support dependable delivery performance."],
    ["Indonesia Production", "Local manufacturing capability serving customers from our Indonesia factory."],
  ];

  return (
    <>
      <main className="relative overflow-hidden bg-white"><div className="grid min-h-[620px] lg:grid-cols-[42%_58%]"><div className="relative z-10 flex items-center px-6 py-20 sm:px-10 lg:px-16 xl:px-24"><div className="max-w-xl"><p className="text-sm font-bold uppercase tracking-[0.28em] text-green-700">Since 2000</p><h1 className="mt-6 text-4xl font-bold leading-tight text-slate-950 sm:text-5xl lg:text-6xl">Connecting Wires.<br /><span className="text-green-700">Connecting Possibilities.</span></h1><p className="mt-6 text-lg leading-8 text-slate-600">DAESOUNG ELECTRIC COMPONENTS specializes in wire harness and electronic component manufacturing, with a commitment to quality, consistency, and long-term partnerships.</p><div className="mt-8 flex flex-wrap gap-4"><a href="/about" className="rounded-lg bg-green-700 px-7 py-3.5 font-semibold text-white transition hover:bg-green-800">LEARN MORE →</a><a href="/products" className="rounded-lg border border-slate-300 px-7 py-3.5 font-semibold text-slate-800 transition hover:border-green-700 hover:text-green-700">OUR PRODUCTS</a></div></div></div><div className="relative min-h-[420px] lg:min-h-full"><img src="/images/factory/factory1.png" alt="DAESOUNG ELECTRIC COMPONENTS manufacturing floor" className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-y-0 left-0 hidden w-40 bg-gradient-to-r from-white via-white/75 to-transparent lg:block" /><div className="absolute inset-x-0 bottom-0 h-28 bg-gradient-to-t from-black/20 to-transparent" /></div></div></main>
      <section className="border-y border-slate-200 bg-slate-50 px-6 py-10"><div className="mx-auto grid max-w-7xl gap-5 sm:grid-cols-2 lg:grid-cols-5"><a href="/products" className="group overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><div className="h-36 overflow-hidden bg-white"><img src="/images/products/이미지 2026. 8. 15. 오전 11.11.png" alt="Wire harness products" className="h-full w-full object-cover object-center transition duration-300 group-hover:scale-105" /></div><div className="p-5"><h2 className="font-bold text-slate-950">Wire Harness</h2><p className="mt-1 text-sm text-slate-500">Harness assemblies</p></div></a><a href="/products" className="group overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><div className="h-36 overflow-hidden bg-white"><img src="/images/products/이미지 2026. 8. 15. 오전 11.27.png" alt="Electronic components" className="h-full w-full object-cover object-center transition duration-300 group-hover:scale-105" /></div><div className="p-5"><h2 className="font-bold text-slate-950">Electronic Components</h2><p className="mt-1 text-sm text-slate-500">Component assemblies</p></div></a><a href="/about" className="group overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><div className="h-36 overflow-hidden"><img src="/images/factory/factory1.png" alt="Manufacturing process" className="h-full w-full object-cover transition duration-300 group-hover:scale-105" /></div><div className="p-5"><h2 className="font-bold text-slate-950">Manufacturing Process</h2><p className="mt-1 text-sm text-slate-500">Stable production systems</p></div></a><a href="/quality" className="group overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><div className="h-36 overflow-hidden bg-white"><img src="/images/quality/%E1%84%8B%E1%85%B5%E1%84%86%E1%85%B5%E1%84%8C%E1%85%B5%202026.%208.%2018.%20%E1%84%8B%E1%85%A9%E1%84%92%E1%85%AE%2012.03.png" alt="Quality inspection line" className="h-full w-full object-cover object-center transition duration-300 group-hover:scale-105" /></div><div className="p-5"><h2 className="font-bold text-slate-950">Quality Management</h2><p className="mt-1 text-sm text-slate-500">Inspection & process control</p></div></a><a href="/contact" className="group overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><div className="h-36 overflow-hidden"><img src="/images/factory/factory0.png" alt="Indonesia factory" className="h-full w-full object-cover transition duration-300 group-hover:scale-105" /></div><div className="p-5"><h2 className="font-bold text-slate-950">Indonesia Factory</h2><p className="mt-1 text-sm text-slate-500">Local manufacturing base</p></div></a></div></section>
      <section className="bg-white px-6 py-20"><div className="mx-auto max-w-7xl"><div className="text-center"><p className="text-sm font-bold uppercase tracking-[0.25em] text-green-700">Our Strength</p><h2 className="mt-3 text-3xl font-bold text-slate-950 md:text-4xl">Why Customers Choose DAESOUNG</h2></div><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-5">{strengths.map(([title, body], index) => (<div key={title} className="rounded-2xl border border-slate-200 bg-slate-50 p-6"><div className="flex h-12 w-12 items-center justify-center rounded-full bg-green-100 text-lg font-bold text-green-800">{String(index + 1).padStart(2, "0")}</div><h3 className="mt-5 font-bold text-slate-950">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{body}</p></div>))}</div></div></section>
      <section className="bg-slate-50 px-6 py-24"><div className="mx-auto max-w-6xl"><div className="grid gap-12 md:grid-cols-2 md:items-center"><div><p className="text-sm font-semibold uppercase tracking-[0.25em] text-green-700">Who We Are</p><h2 className="mt-4 text-4xl font-bold text-slate-900 md:text-5xl">Building Trust Through Quality</h2><p className="mt-6 text-lg leading-8 text-slate-600">DAESOUNG ELECTRIC COMPONENTS is a manufacturing company specializing in wire harnesses and electronic component solutions.</p><p className="mt-5 text-lg leading-8 text-slate-600">Established in October 2000, we have continuously strengthened our manufacturing capabilities while building long-term partnerships with customers and business partners.</p><a href="/about" className="mt-8 inline-block rounded-full bg-green-700 px-8 py-3 font-semibold text-white transition hover:bg-green-800">LEARN MORE</a></div><div className="overflow-hidden rounded-3xl shadow-xl"><img src="/images/factory/factory1.png" alt="DAESOUNG ELECTRIC COMPONENTS production facility" className="h-full min-h-[360px] w-full object-cover" /></div></div></div></section>
      <section className="bg-white px-6 py-24"><div className="mx-auto max-w-6xl text-center"><p className="text-sm font-semibold uppercase tracking-[0.25em] text-green-700">Our Products</p><h2 className="mt-4 text-4xl font-bold text-slate-900 md:text-5xl">Wire Harness Solutions</h2><p className="mx-auto mt-5 max-w-2xl text-lg leading-8 text-slate-600">Reliable wire harness and electronic component solutions designed to meet customer requirements and product specifications.</p><div className="mt-14 overflow-hidden rounded-3xl border border-slate-200 bg-white p-3 shadow-sm"><img src="/images/products/products.png" alt="DAESOUNG ELECTRIC COMPONENTS product portfolio" className="h-auto w-full rounded-2xl object-contain" /></div><a href="/products" className="mt-10 inline-block rounded-full border border-green-700 px-8 py-3 font-semibold text-green-700 transition hover:bg-green-700 hover:text-white">VIEW ALL PRODUCTS</a></div></section>
      <section className="bg-slate-950 px-6 py-20 text-white"><div className="mx-auto grid max-w-6xl gap-10 md:grid-cols-[1.2fr_1fr] md:items-center"><div><p className="text-sm font-semibold uppercase tracking-[0.25em] text-green-400">Quality & Reliability</p><h2 className="mt-4 text-4xl font-bold md:text-5xl">Quality Comes First</h2><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-300">We maintain consistent quality throughout the manufacturing process, from incoming materials to final inspection and delivery.</p><a href="/quality" className="mt-8 inline-block rounded-full bg-green-600 px-8 py-3 font-semibold text-white transition hover:bg-green-500">OUR QUALITY</a></div><div className="grid gap-4 sm:grid-cols-3 md:grid-cols-1">{["Incoming Inspection", "Process Control", "Final Inspection"].map((item, index) => <div key={item} className="rounded-2xl border border-white/10 bg-white/5 p-5"><span className="text-green-400">0{index + 1}</span><p className="mt-2 font-semibold">{item}</p></div>)}</div></div></section>
      <section className="bg-white px-6 py-20 text-center"><p className="text-sm font-semibold uppercase tracking-[0.25em] text-green-700">Let&apos;s Work Together</p><h2 className="mt-4 text-4xl font-bold text-slate-900 md:text-5xl">Your Trusted Manufacturing Partner</h2><p className="mx-auto mt-5 max-w-3xl text-lg leading-8 text-slate-600">Connect with DAESOUNG ELECTRIC COMPONENTS for reliable wire harness solutions, electronic components, and customized manufacturing solutions tailored to your needs.</p><a href="/contact" className="mt-8 inline-block rounded-full bg-green-700 px-10 py-4 font-semibold text-white transition hover:bg-green-800">CONTACT US</a></section>
    </>
  );
}
